- name: set hosts configuration
  template:
    src: hosts.j2
    dest: /etc/hosts

- name: disable firewall
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: remove swap from grub
  replace:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX="crashkernel=auto rd\.lvm\.lv=centos\/root rd\.lvm\.lv=centos\/swap rhgb quiet"$'
    replace: GRUB_CMDLINE_LINUX="crashkernel=auto rd.lvm.lv=centos/root rhgb quiet"
  notify:
    - swap removed from grub