- name: install squid
  yum: name=squid

- name: enable cache
  replace:
    path: /etc/squid/squid.conf
    regexp: "^#cache_dir ufs /var/spool/squid 100 16 256$"
    replace: cache_dir ufs /var/spool/squid 7000 16 256
  notify:
    - restart squid

- name: disable firewall
  systemd:
    name: firewalld
    state: stopped
    enabled: no
