- name: install flannel
  yum: name=flannel

- name: create kubernetes configuration directory
  file:
    path: /etc/kubernetes
    state: directory

- name: add kubernetes configuration
  copy:
    src: kube_config
    dest: /etc/kubernetes/config

- name: add flannel configuration
  template:
    src: flanneld.j2
    dest: /etc/sysconfig/flanneld
  notify:
    - restart flannel
